# Generated by Django 6.0.2 on 2026-02-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['order'], 'verbose_name': 'Кейс', 'verbose_name_plural': 'Кейсы'},
        ),
        migrations.AlterModelOptions(
            name='caseimage',
            options={'ordering': ['order'], 'verbose_name': 'Фото кейса', 'verbose_name_plural': 'Фото кейсов'},
        ),
        migrations.AlterModelOptions(
            name='doctorfact',
            options={'ordering': ['order'], 'verbose_name': 'Факт', 'verbose_name_plural': 'Факты'},
        ),
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'verbose_name': 'Доктор', 'verbose_name_plural': 'Доктора'},
        ),
        migrations.AlterModelOptions(
            name='homefeature',
            options={'ordering': ['order'], 'verbose_name': 'Преимущество', 'verbose_name_plural': 'Преимущества'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Главная страница', 'verbose_name_plural': 'Главная страница'},
        ),
        migrations.AlterModelOptions(
            name='homestat',
            options={'ordering': ['order'], 'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['order'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Настройки сайта', 'verbose_name_plural': 'Настройки сайта'},
        ),
        migrations.AlterField(
            model_name='case',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='case',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_primary_text',
            field=models.CharField(default='Записаться', max_length=50, verbose_name='Первая кнопка'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_primary_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='URL первой кнопки'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_secondary_text',
            field=models.CharField(default='Посмотреть 360° тур', max_length=50, verbose_name='Вторая кнопка'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_secondary_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='URL второй кнопки'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='final_cta_primary_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='Первая кнопка CTA'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='final_cta_primary_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='URL первой CTA'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='final_cta_secondary_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='Вторая CTA'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='final_cta_secondary_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='URL второй CTA'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='final_cta_text',
            field=models.TextField(blank=True, verbose_name='Текст CTA'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='final_cta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок CTA'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_badge',
            field=models.CharField(blank=True, max_length=120, verbose_name='Бейдж'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_bg',
            field=models.ImageField(blank=True, null=True, upload_to='home/', verbose_name='Фон'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(blank=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='services_all_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='URL всех услуг'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='services_subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок услуг'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='services_title',
            field=models.CharField(default='Наши услуги', max_length=120, verbose_name='Заголовок услуг'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='tour_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/', verbose_name='Фото тура'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='tour_subtitle',
            field=models.TextField(blank=True, verbose_name='Подзаголовок тура'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='tour_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок тура'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='tour_url',
            field=models.URLField(blank=True, verbose_name='URL тура'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='trust_subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок доверия'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='trust_title',
            field=models.CharField(default='Почему нам доверяют', max_length=120, verbose_name='Заголовок доверия'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='homestat',
            name='label',
            field=models.CharField(max_length=80, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='homestat',
            name='value',
            field=models.CharField(max_length=30, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_name',
            field=models.CharField(default='Dr. Eliyar', max_length=120, verbose_name='Название бренда'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_tagline',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подпись бренда'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram',
            field=models.URLField(blank=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.URLField(blank=True, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='work_time',
            field=models.CharField(blank=True, max_length=120, verbose_name='Время работы'),
        ),
    ]
