version: "3.8"

services:
  db_dreliar:
    image: postgres:14
    container_name: postgres_db_dreliar
    env_file:
      - ../.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_dreliar:/var/lib/postgresql/data
    networks:
      - portfolio_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis_dreliar:
    image: redis:6
    container_name: redis_dreliar
    ports:
      - "6389:6379"
    networks:
      - portfolio_network

  web_dreliar:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: django_web_dreliar
    env_file:
      - ../.env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    volumes:
      - ../app:/app
      - ../app/static:/app/static
      - ../app/media:/app/media
    depends_on:
      db_dreliar:
        condition: service_healthy
      redis_dreliar:
        condition: service_started
    ports:
      - "127.0.0.1:8084:8082"
    networks:
      - portfolio_network

  # telegram_bot:
  #   build:
  #     context: ..
  #     dockerfile: docker/Dockerfile
  #   container_name: telegram_bot_dreliar
  #   env_file:
  #     - ../.env
  #   volumes:
  #     - ../app:/app
  #   depends_on:
  #     db_dreliar:
  #       condition: service_healthy
  #     web_dreliar:
  #       condition: service_started
  #   networks:
  #     - portfolio_network
  #   command: python bot.py

networks:
  portfolio_network:
    driver: bridge

volumes:
  postgres_data_dreliar: