# Generated by Django 6.0.2 on 2026-02-25 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('tag', models.CharField(blank=True, max_length=80, verbose_name='Тег')),
                ('duration', models.CharField(blank=True, max_length=80, verbose_name='Длительность')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('role', models.CharField(blank=True, max_length=120, verbose_name='Должность')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctor/', verbose_name='Фото')),
                ('details_url', models.CharField(blank=True, max_length=255, verbose_name='Ссылка/slug')),
            ],
            options={
                'verbose_name': 'Доктор',
                'verbose_name_plural': 'Доктора',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('hero_badge', models.CharField(blank=True, max_length=120, verbose_name='Бейдж')),
                ('hero_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('hero_subtitle', models.TextField(blank=True, verbose_name='Подзаголовок')),
                ('hero_bg', models.ImageField(blank=True, null=True, upload_to='home/', verbose_name='Фон')),
                ('trust_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок доверия')),
                ('trust_subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок доверия')),
                ('services_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок услуг')),
                ('services_subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок услуг')),
                ('our_command_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок команды')),
                ('our_command_subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок команды')),
                ('tur_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок туров')),
                ('tur_subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок туров')),
                ('doctor_name', models.CharField(blank=True, max_length=255, verbose_name='Имя доктора')),
                ('doctor_subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок доктора')),
                ('doctor_description', models.TextField(blank=True, verbose_name='Описание доктора')),
                ('doctor_patients', models.IntegerField(blank=True, null=True, verbose_name='Количество пациентов')),
                ('doctor_experience', models.IntegerField(blank=True, null=True, verbose_name='Опыт работы')),
                ('doctor_courses', models.IntegerField(blank=True, null=True, verbose_name='Количество курсов')),
                ('result_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок результата')),
                ('result_subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок результата')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='home/result/', verbose_name='Изображение результата')),
                ('review_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок отзыва')),
                ('review_subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок отзыва')),
                ('consultation_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок консультации')),
                ('consultation_subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок консультации')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('text', models.TextField(verbose_name='Текст')),
                ('author_name', models.CharField(max_length=120, verbose_name='Автор')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Оценка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена от')),
                ('currency', models.CharField(default='сум', max_length=10, verbose_name='Валюта')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('brand_name', models.CharField(default='Dr. Eliyar', max_length=120, verbose_name='Название бренда')),
                ('brand_tagline', models.CharField(blank=True, max_length=255, verbose_name='Подпись бренда')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('work_time', models.CharField(blank=True, max_length=120, verbose_name='Время работы')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('whatsapp', models.URLField(blank=True, verbose_name='WhatsApp')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='CaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('before', 'Before'), ('after', 'After')], max_length=10, verbose_name='Тип')),
                ('image', models.ImageField(upload_to='cases/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.case')),
            ],
            options={
                'verbose_name': 'Фото кейса',
                'verbose_name_plural': 'Фото кейсов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DoctorFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='pages.doctorprofile')),
            ],
            options={
                'verbose_name': 'Факт',
                'verbose_name_plural': 'Факты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pages.homepage')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30, verbose_name='Значение')),
                ('label', models.CharField(max_length=80, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='pages.homepage')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
                'ordering': ['order'],
            },
        ),
    ]
