# Generated by Django 6.0.2 on 2026-02-24 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('tag', models.CharField(blank=True, max_length=80)),
                ('duration', models.CharField(blank=True, max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('specialty', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctor/')),
                ('details_url', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Доктор',
                'verbose_name_plural': 'Доктора',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('hero_badge', models.CharField(blank=True, max_length=120, verbose_name='Бейдж')),
                ('hero_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('hero_subtitle', models.TextField(blank=True, verbose_name='Подзаголовок')),
                ('hero_bg', models.ImageField(blank=True, null=True, upload_to='home/', verbose_name='Фон')),
                ('cta_primary_text', models.CharField(default='Записаться', max_length=50, verbose_name='Первая кнопка')),
                ('cta_primary_url', models.CharField(blank=True, max_length=255, verbose_name='URL первой кнопки')),
                ('cta_secondary_text', models.CharField(default='Посмотреть 360° тур', max_length=50, verbose_name='Вторая кнопка')),
                ('cta_secondary_url', models.CharField(blank=True, max_length=255, verbose_name='URL второй кнопки')),
                ('trust_title', models.CharField(default='Почему нам доверяют', max_length=120, verbose_name='Заголовок доверия')),
                ('trust_subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок доверия')),
                ('services_title', models.CharField(default='Наши услуги', max_length=120, verbose_name='Заголовок услуг')),
                ('services_subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок услуг')),
                ('services_all_url', models.CharField(blank=True, max_length=255, verbose_name='URL всех услуг')),
                ('tour_title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок тура')),
                ('tour_subtitle', models.TextField(blank=True, verbose_name='Подзаголовок тура')),
                ('tour_image', models.ImageField(blank=True, null=True, upload_to='home/', verbose_name='Фото тура')),
                ('tour_url', models.URLField(blank=True, verbose_name='URL тура')),
                ('final_cta_title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок CTA')),
                ('final_cta_text', models.TextField(blank=True, verbose_name='Текст CTA')),
                ('final_cta_primary_text', models.CharField(blank=True, max_length=50, verbose_name='Первая кнопка CTA')),
                ('final_cta_primary_url', models.CharField(blank=True, max_length=255, verbose_name='URL первой CTA')),
                ('final_cta_secondary_text', models.CharField(blank=True, max_length=50, verbose_name='Вторая CTA')),
                ('final_cta_secondary_url', models.CharField(blank=True, max_length=255, verbose_name='URL второй CTA')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('text', models.TextField()),
                ('author_name', models.CharField(max_length=120)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price_from', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='сум', max_length=10)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('brand_name', models.CharField(default='Dr. Eliyar', max_length=120, verbose_name='Название бренда')),
                ('brand_tagline', models.CharField(blank=True, max_length=255, verbose_name='Подпись бренда')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('work_time', models.CharField(blank=True, max_length=120, verbose_name='Время работы')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('whatsapp', models.URLField(blank=True, verbose_name='WhatsApp')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='CaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('before', 'Before'), ('after', 'After')], max_length=10)),
                ('image', models.ImageField(upload_to='cases/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.case')),
            ],
            options={
                'verbose_name': 'Фото кейса',
                'verbose_name_plural': 'Фото кейсов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DoctorFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='pages.doctorprofile')),
            ],
            options={
                'verbose_name': 'Факт',
                'verbose_name_plural': 'Факты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pages.homepage')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30, verbose_name='Значение')),
                ('label', models.CharField(max_length=80, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='pages.homepage')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
                'ordering': ['order'],
            },
        ),
    ]
