# Generated by Django 6.0.2 on 2026-02-25 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='details_url',
        ),
        migrations.DeleteModel(
            name='DoctorFact',
        ),
    ]
