# Generated by Django 6.0.2 on 2026-02-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_doctorprofile_details_url_delete_doctorfact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homefeature',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='home/feature/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='service/', verbose_name='Иконка'),
        ),
    ]
