# Generated by Django 6.0.2 on 2026-02-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_homefeature_icon_alter_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='doctor_photo',
            field=models.ImageField(blank=True, null=True, upload_to='home/doctor/', verbose_name='Фото доктора'),
        ),
    ]
