# Generated by Django 6.0.2 on 2026-02-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_homepage_doctor_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='brand_tagline',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='work_time',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='weekdays',
            field=models.CharField(blank=True, max_length=120, verbose_name='Режим работы'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='weekends',
            field=models.CharField(blank=True, max_length=120, verbose_name='Режим работы'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube',
            field=models.URLField(blank=True, verbose_name='YouTube'),
        ),
    ]
