# Generated by Django 6.0.2 on 2026-02-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_result_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Аватар'),
        ),
    ]
