# Generated by Django 6.0.2 on 2026-02-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_review_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(default=5, verbose_name='Оценка'),
        ),
    ]
