# Generated by Django 6.0.2 on 2026-02-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='doctor_recommend',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество рекомендаций'),
        ),
    ]
