# Generated by Django 6.0.2 on 2026-02-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_doctorprofile_subtitle_homepage_doctor_recommend'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTheClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('philosophy_title', models.CharField(max_length=120, verbose_name='Заголовок философии')),
                ('philosophy_description', models.TextField(verbose_name='Описание философии')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='about_the_clinic/icon/', verbose_name='Иконка')),
                ('philosophy_title_icon', models.CharField(max_length=120, verbose_name='Заголовок иконки')),
                ('philosophy_description_icon', models.TextField(verbose_name='Описание иконки')),
                ('interior_title', models.CharField(max_length=120, verbose_name='Заголовок интерьера')),
                ('interior_description', models.TextField(verbose_name='Описание интерьера')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about_the_clinic/photo/', verbose_name='Фото')),
                ('certificates_icon', models.ImageField(blank=True, null=True, upload_to='about_the_clinic/certificates/', verbose_name='Иконка сертификатов')),
                ('certificates_title', models.CharField(max_length=120, verbose_name='Заголовок сертификатов')),
                ('certificates_description', models.TextField(verbose_name='Описание сертификатов')),
                ('personally_title', models.CharField(max_length=120, verbose_name='Заголовок персонально')),
                ('personally_description', models.TextField(verbose_name='Описание персонально')),
            ],
            options={
                'verbose_name': 'О клинике',
                'verbose_name_plural': 'О клинике',
            },
        ),
    ]
