# Generated by Django 6.0.2 on 2026-02-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_abouttheclinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_the_clinic/certificates/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='Interior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_the_clinic/interior/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Интерьер',
                'verbose_name_plural': 'Интерьер',
            },
        ),
        migrations.CreateModel(
            name='Philosophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='about_the_clinic/philosophy/', verbose_name='Иконка')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Философия',
                'verbose_name_plural': 'Философия',
            },
        ),
        migrations.RemoveField(
            model_name='abouttheclinic',
            name='certificates_icon',
        ),
        migrations.RemoveField(
            model_name='abouttheclinic',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='abouttheclinic',
            name='philosophy_description_icon',
        ),
        migrations.RemoveField(
            model_name='abouttheclinic',
            name='philosophy_title_icon',
        ),
        migrations.RemoveField(
            model_name='abouttheclinic',
            name='photo',
        ),
    ]
