# Generated by Django 6.0.2 on 2026-02-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_certificates_interior_philosophy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='subtitle',
            field=models.CharField(blank=True, max_length=20, verbose_name='Подзаголовок'),
        ),
    ]
