# Generated by Django 6.0.2 on 2026-02-25 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_doctorprofile_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='philosophy',
            name='about',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='philosophies', to='pages.abouttheclinic'),
        ),
    ]
