# Generated by Django 6.0.2 on 2026-02-26 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_philosophy_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='about',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='pages.abouttheclinic', verbose_name='О клинике'),
        ),
        migrations.AlterField(
            model_name='philosophy',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='philosophies', to='pages.abouttheclinic', verbose_name='О клинике'),
        ),
    ]
