# Generated by Django 6.0.2 on 2026-02-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_certificates_about_alter_philosophy_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificates',
            name='about',
        ),
    ]
