# Generated by Django 6.0.2 on 2026-02-26 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_remove_certificates_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='philosophy',
            name='about',
        ),
    ]
