# Generated by Django 6.0.2 on 2026-03-01 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_certificates_about_interior_about_philosophy_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
