# Generated by Django 6.0.2 on 2026-03-02 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultsIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('tag', models.CharField(blank=True, max_length=80, verbose_name='Тег')),
                ('duration', models.CharField(blank=True, max_length=80, verbose_name='Длительность')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='caseimage',
            name='case',
        ),
        migrations.CreateModel(
            name='ResultsIndexImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('before', 'Before'), ('after', 'After')], max_length=10, verbose_name='Тип')),
                ('image', models.ImageField(upload_to='cases/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.resultsindex')),
            ],
            options={
                'verbose_name': 'Фото кейса',
                'verbose_name_plural': 'Фото кейсов',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='CaseImage',
        ),
    ]
