# Generated by Django 6.0.2 on 2026-03-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_resultsindex_remove_caseimage_case_resultsindeximage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('problem', models.CharField(max_length=255, verbose_name='Проблема')),
                ('date', models.CharField(max_length=255, verbose_name='Дата')),
                ('fear', models.CharField(max_length=255, verbose_name='Страх')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Запись в чат',
                'verbose_name_plural': 'Записи в чат',
            },
        ),
    ]
