# Generated by Django 6.0.2 on 2026-03-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название услуги')),
                ('description', models.TextField(verbose_name='описание услуги')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('price', models.IntegerField(verbose_name='цена услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServicesBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('record_service_title', models.CharField(max_length=255, verbose_name='название записи')),
                ('record_service_description', models.TextField(verbose_name='описание записи')),
            ],
            options={
                'verbose_name': 'баннер услуги',
            },
        ),
        migrations.CreateModel(
            name='ServicesHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='services_home/', verbose_name='Фото')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Услуга на главной',
                'verbose_name_plural': 'Услуги на главной',
            },
        ),
    ]
