# Generated by Django 6.0.2 on 2026-02-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patients', models.IntegerField(verbose_name='Количество пациентов')),
                ('average_rating', models.IntegerField(verbose_name='средний рейтинг ')),
                ('recommend', models.IntegerField(verbose_name='рекомендуют нас')),
                ('reviews_online', models.IntegerField(verbose_name='отзывов онлайн')),
                ('vidio', models.FileField(upload_to='reviews/vidio/', verbose_name='Видео')),
                ('title_vidio', models.CharField(max_length=255, verbose_name='Название')),
                ('text_rating', models.FloatField(verbose_name='рейтинга')),
                ('text_description', models.TextField(verbose_name='Описание')),
                ('avatar', models.ImageField(upload_to='reviews/', verbose_name='Аватар')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('time', models.CharField(max_length=255, verbose_name='Время')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('record_title', models.CharField(max_length=255, verbose_name='Название Присоединяйтесь к 5 000+ довольных пациентов')),
                ('description_record', models.TextField(verbose_name='Описание Присоединяйтесь к 5 000+ довольных пациентов')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
