# Generated by Django 6.0.2 on 2026-03-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patients', models.IntegerField(verbose_name='Количество пациентов')),
                ('average_rating', models.FloatField(verbose_name='Средний рейтинг')),
                ('recommend', models.IntegerField(verbose_name='Процент рекомендаций')),
                ('reviews_online', models.IntegerField(verbose_name='Отзывов онлайн')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
        migrations.CreateModel(
            name='VideoReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='reviews/video/', verbose_name='Видео')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Видео отзыв',
                'verbose_name_plural': 'Видео отзывы',
            },
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Текстовый отзыв', 'verbose_name_plural': 'Текстовые отзывы'},
        ),
        migrations.RemoveField(
            model_name='review',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='patients',
        ),
        migrations.RemoveField(
            model_name='review',
            name='recommend',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviews_online',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title_vidio',
        ),
        migrations.RemoveField(
            model_name='review',
            name='vidio',
        ),
        migrations.AlterField(
            model_name='review',
            name='text_description',
            field=models.TextField(verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text_rating',
            field=models.FloatField(verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='review',
            name='time',
            field=models.CharField(max_length=255, verbose_name='Дата / Тип лечения'),
        ),
        migrations.AlterField(
            model_name='reviewbanner',
            name='description_record',
            field=models.TextField(verbose_name='Описание блока Присоединяйтесь'),
        ),
        migrations.AlterField(
            model_name='reviewbanner',
            name='record_title',
            field=models.CharField(max_length=255, verbose_name='Заголовок блока Присоединяйтесь'),
        ),
    ]
