# Generated by Django 6.0.2 on 2026-02-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageOne', models.ImageField(upload_to='cases/', verbose_name='Изображение 1')),
                ('imageTwo', models.ImageField(upload_to='cases/', verbose_name='Изображение 2')),
                ('type', models.CharField(max_length=255, verbose_name='Тип')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('term', models.CharField(max_length=255, verbose_name='Срок')),
                ('quantity', models.CharField(max_length=255, verbose_name='Количество')),
                ('result', models.CharField(max_length=255, verbose_name='Результат')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
            },
        ),
        migrations.CreateModel(
            name='CasesBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('title_record', models.CharField(max_length=255, verbose_name='Название Хотите такой же результат?')),
                ('description_record', models.TextField(verbose_name='Описание Хотите такой же результат?')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
