# Generated by Django 6.0.2 on 2026-02-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='ContactsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addres', models.CharField(max_length=255, verbose_name='Адрес')),
                ('landmark', models.CharField(max_length=255, verbose_name='Ориентир')),
                ('weekdays', models.CharField(max_length=255, verbose_name='Пн–Пт')),
                ('saturday', models.CharField(max_length=255, verbose_name='Суббота')),
                ('sunday', models.CharField(max_length=255, verbose_name='Воскресенье')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('whatsapp', models.URLField(max_length=255, verbose_name='WhatsApp')),
                ('telegram', models.URLField(max_length=255, verbose_name='Telegram')),
                ('instagram', models.URLField(max_length=255, verbose_name='инстаграм')),
                ('map', models.TextField(blank=True, verbose_name='Карта (iframe)')),
            ],
        ),
    ]
