# Generated by Django 6.0.2 on 2026-02-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True)),
                ('reason', models.CharField(blank=True, max_length=80)),
                ('source', models.CharField(choices=[('hero', 'Hero button'), ('services', 'Service card'), ('quick', 'Quick widget'), ('cta', 'Final CTA'), ('call', 'Call button'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
    ]
