# Generated by Django 6.0.2 on 2026-03-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('service', models.CharField(choices=[('consultation', 'Консультация'), ('implant', 'Имплантация'), ('veneers', 'Виниры / Коронки'), ('caries', 'Лечение кариеса'), ('ortho', 'Ортодонтия'), ('surgery', 'Хирургия'), ('hygiene', 'Гигиена / Отбеливание'), ('children', 'Детская стоматология'), ('other', 'Другое')], max_length=50, verbose_name='Услуга')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Запись на приём',
                'verbose_name_plural': 'Записи на приём',
            },
        ),
        migrations.AlterField(
            model_name='contactsinfo',
            name='instagram',
            field=models.URLField(max_length=255, verbose_name='Instagram'),
        ),
    ]
