# Generated by Django 6.0.2 on 2026-03-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_booking_alter_contactsinfo_instagram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запись на приём', 'verbose_name_plural': 'Записи на приём'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('Консультация', 'Консультация'), ('Имплантация', 'Имплантация'), ('Виниры / Коронки', 'Виниры / Коронки'), ('Лечение кариеса', 'Лечение кариеса'), ('Ортодонтия', 'Ортодонтия'), ('Хирургия', 'Хирургия'), ('Гигиена / Отбеливание', 'Гигиена / Отбеливание'), ('Детская стоматология', 'Детская стоматология'), ('Другое', 'Другое')], max_length=255, verbose_name='Услуга'),
        ),
    ]
