# Generated by Django 6.0.2 on 2026-03-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTheClinicBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('title_our_team', models.CharField(max_length=120, verbose_name='Заголовок Наша команда')),
                ('description_our_team', models.TextField(verbose_name='Описание Наша команда')),
                ('title_philosophy', models.CharField(max_length=120, verbose_name='Заголовок Философия')),
                ('description_philosophy', models.TextField(verbose_name='Описание Философия')),
                ('title_interior', models.CharField(max_length=120, verbose_name='Заголовок Интерьер')),
                ('description_interior', models.TextField(verbose_name='Описание Интерьер')),
                ('title_certificates', models.CharField(max_length=120, verbose_name='Заголовок Сертификаты')),
                ('description_certificates', models.TextField(verbose_name='Описание Сертификаты')),
                ('title_recors', models.CharField(max_length=120, verbose_name='Заголовок Познакомимся лично?')),
                ('description_recors', models.TextField(verbose_name='Описание Познакомимся лично?')),
            ],
            options={
                'verbose_name': 'Баннер О клинике',
                'verbose_name_plural': 'Баннеры О клинике',
            },
        ),
        migrations.CreateModel(
            name='AboutTheClinicCertificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='about_the_clinic/', verbose_name='Иконка')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Сертификаты',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='AboutTheClinicDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_doctor', models.ImageField(upload_to='about_the_clinic/', verbose_name='Фото врача')),
                ('doctor_position', models.CharField(max_length=120, verbose_name='Должность')),
                ('doctor_name', models.CharField(max_length=120, verbose_name='Имя врача')),
                ('doctor_subtitle', models.CharField(max_length=120, verbose_name='Подзаголовок')),
                ('doctor_description', models.TextField(verbose_name='Описание')),
                ('patients', models.IntegerField(verbose_name='Количество пациентов')),
                ('experience', models.IntegerField(verbose_name='Стаж работы')),
                ('courses', models.IntegerField(verbose_name='Количество курсов')),
                ('recommend', models.IntegerField(verbose_name='Рекомендаций')),
            ],
            options={
                'verbose_name': 'Врач клиники',
                'verbose_name_plural': 'Врачи клиники',
            },
        ),
        migrations.CreateModel(
            name='AboutTheClinicInterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='about_the_clinic/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Интерьер',
                'verbose_name_plural': 'Интерьеры',
            },
        ),
        migrations.CreateModel(
            name='AboutTheClinicOurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='about_the_clinic/', verbose_name='Фото')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('position', models.CharField(max_length=120, verbose_name='Должность')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Наша команда',
                'verbose_name_plural': 'Наша команда',
            },
        ),
        migrations.CreateModel(
            name='AboutTheClinicPhilosophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='about_the_clinic/', verbose_name='Иконка')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Философия',
                'verbose_name_plural': 'Философия',
            },
        ),
    ]
