# Generated by Django 6.0.2 on 2026-02-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TurBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('title_clinik', models.CharField(max_length=255, verbose_name='Название что внутри клиники ')),
                ('description_clinik', models.TextField(verbose_name='Описание что внутри клиники')),
                ('record_title', models.CharField(max_length=255, verbose_name=' название Хотите увидеть клинику лично?')),
                ('record_description', models.TextField(verbose_name='Описание Хотите увидеть клинику лично?')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.CreateModel(
            name='TurClinik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='tur_clinik/', verbose_name='Иконка')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Клиника',
                'verbose_name_plural': 'Клиники',
            },
        ),
    ]
