# Generated by Django 6.0.2 on 2026-03-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbanner',
            name='description_clinik',
            field=models.TextField(verbose_name="Описание блока 'Что внутри клиники'"),
        ),
        migrations.AlterField(
            model_name='turbanner',
            name='record_description',
            field=models.TextField(verbose_name='Описание CTA'),
        ),
        migrations.AlterField(
            model_name='turbanner',
            name='record_title',
            field=models.CharField(max_length=255, verbose_name='Заголовок CTA'),
        ),
        migrations.AlterField(
            model_name='turbanner',
            name='title_clinik',
            field=models.CharField(max_length=255, verbose_name="Заголовок блока 'Что внутри клиники'"),
        ),
    ]
